---
galaxy_info:
  author: Jacob Johansen
  description: Enables IOMMU and configures vfio-pci on ubuntu
  license: MIT
  min_ansible_version: 2.3

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - system
    - hardware
    - vfio
    - iommu
