---
- name: tcp_fin_timeout
  sysctl: 
    name: net.ipv4.tcp_fin_timeout 
    value: 15
    reload: true 

- name: tcp_slow_start_after_idle
  sysctl: 
    name: net.ipv4.tcp_slow_start_after_idle 
    value: 0
    reload: true

- name: ip_local_port_range
  sysctl: 
    name: net.ipv4.ip_local_port_range 
    value: "1024 65000" 
    reload: true

- name: tcp_synack_retries
  sysctl: 
    name: net.ipv4.tcp_synack_retries 
    value: 2
    reload: true 

- name: tcp_rfc1337
  sysctl: 
    name: net.ipv4.tcp_rfc1337 
    value: 1
    reload: true 

- name: tcp_keepalive_time
  sysctl: 
    name: net.ipv4.tcp_keepalive_time 
    value: 300
    reload: true 

- name: tcp_keepalive_probes
  sysctl: 
    name: net.ipv4.tcp_keepalive_probes 
    value: 5
    reload: true 

- name: tcp_keepalive_intvl
  sysctl: 
    name: net.ipv4.tcp_keepalive_intvl 
    value: 15
    reload: true 

- name: rmem_max
  sysctl: 
    name: net.core.rmem_max 
    value: 8388608 
    reload: true

- name: wmem_max
  sysctl: 
    name: net.core.wmem_max 
    value: 8388608 
    reload: true

- name: rmem_default
  sysctl: 
    name: net.core.rmem_default 
    value: 65536
    reload: true 

- name: wmem_default
  sysctl: 
    name: net.core.wmem_default 
    value: 65536
    reload: true 

- name: tcp_rmem
  sysctl: 
    name: net.ipv4.tcp_rmem 
    value: "8192 873800 8388608" 
    reload: true

- name: tcp_wmem
  sysctl: 
    name: net.ipv4.tcp_wmem 
    value: "4092 655360 8388608" 
    reload: true

- name: somaxconn
  sysctl: 
    name: net.core.somaxconn 
    value: 4096 
    reload: true

- name: swappiness
  sysctl: 
    name: vm.swappiness 
    value: 10
    reload: true 

- name: dirty_ratio
  sysctl: 
    name: vm.dirty_ratio 
    value: 60
    reload: true 

- name: dirty_background_ratio
  sysctl: 
    name: vm.dirty_background_ratio 
    value: 2
    reload: true 

- name: vfs_cache_pressure
  sysctl: 
    name: vm.vfs_cache_pressure 
    value: 50
    reload: true 

- name: Increase user soft nofile limits
  pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 64000

- name: Increase user hard nofile limits
  pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 64000

- name: Increase root soft nofile limits
  pam_limits:
    domain: root
    limit_type: soft
    limit_item: nofile
    value: 64000

- name: Increase root hard nofile limits
  pam_limits:
    domain: root
    limit_type: hard
    limit_item: nofile
    value: 64000

- name: Increase root hard memlock limits
  pam_limits:
    domain: root
    limit_type: hard
    limit_item: memlock
    value: unlimited

- name: Increase root soft memlock limits
  pam_limits:
    domain: root
    limit_type: soft
    limit_item: memlock
    value: unlimited

- name: Increase root hard nproc limits
  pam_limits:
    domain: root
    limit_type: hard
    limit_item: nproc
    value: 131072

- name: Increase root soft nproc limits
  pam_limits:
    domain: root
    limit_type: soft
    limit_item: nproc
    value: 131072


- name: reload settings from all system configuration files
  shell: sysctl --system