---
# Called in templates/vfio-modprobe.conf.j2
ids_to_pass: '{{ vfio_pci_ids|join(",") }}'

# ansible_processor is a list (!) set up like:
# [ core number, vendor, model, core number, vendor, model, ... ]
cpu_vendor: "{{ ansible_facts['processor'][1] | lower | regex_replace('(authentic)|(genuine)', '') }}"
iommu_kernel_option: '{{ cpu_vendor }}_iommu'
iommu_kernel_value: 'on'
iommu_pt_kernel_option: 'iommu'
iommu_pt_kernel_value: 'pt'
vfio_pci_kernel_option: 'vfio-pci.ids'
vfio_pci_kernel_value: '{{ ids_to_pass }}'